# ELP Detections and Sampling Effort

# This script reads in three data-types
# - Event detection data (requires columns 'Begin File', 'File Offset', 'Count' and 'Dep Num')
# - Gunshot detection data (requires columns 'Begin File', 'File Offset', 'Count' and 'Dep Num')
# - Zero days data to account for sampling effort (requires columns 'Begin File')
# - sound check files


# CAUTION
# Some of these files may not have been updated after changes were made to sound file names, times, subsequent discoveries in poor sound quality, etc.
# This script assumes all the tables are up-to-date. All changes should be updated in these files before they are loaded in .R
# this does not yet include bad dates from the SwiftOne gain setting issue

# bje37@cornell.edu
# updated: Sept 2023

## TO DO ##
# plot mean Events per sampled date to account for sampling effort
# enable option for gunshot tables? Or just just one detector folder instead
# remove dates that are not listed in sound check file? (optional) - shouldn't this already be happening by only marking 'good' dates from Event SSTs?

#' @title Data Summaries
#' @author Bobbi J. Estabrook <bobbi.estabrook@cornell.edu>
#'
#' @description
#' This function summarizes data from the annotated selection tables, the sound check files, and the zero-days selection tables into hourly, daily, weekly, and monthly time periods.
#' The summaries will yield .txt files containing summary data and an .rds file containing plots.
#' This function will:
#' \itemize{
#' \item Install and load necessary packages
#' \item Read in data provided by the user (sound check files, random dates, selection tables, zero-day tables, sites file)
#' \item Generate summary tables and plots that are saved to /data_summaries/summary_tables and /data_summaries/summary_plots, respectively
#' }
#'
#' @param parent_dir Folder containing the specific elpR sub-folder structure
#' @param project_name Project name (e.g., PNNN, DzangaBai, Kakum)
#' @param deployment_num Deployment(s) number (e.g., 01-12, 04)
#' @param detector_name Detector used (e.g., HoriHarm, FruitPunchAI, Stanford Detector)
#' @param event_count_column Name of the input column containing event counts
#' @param selection_tables Folder containing selection tables
#' @param zero_txt Folder containing zero-days files generated by restrucutre_Event_function()
#' @param sound_check_include If you have sound check .xlsx files for this script to filter out bad sounds (y/n)
#' @param sound_checks Folder containing sound check .xlsx files
#' @param use_only_sites_provided If you want to include only the sites listed in a site_lat_long file (y/n)
#' @param site_lat_long A .txt file containing site names with latitude, longitude, vegetation class (optional), strata (optional): See existing files in the "elpR/Files/sites" folder for required structure of .txt file
#' @param rand_dates_needed If you want 3 random days per week (y/n) *dates are pre-selected in the /rand-days/Rand_dates.csv file
#' @param events_bad_sound_remove If you want to exclude sounds with less than 23 hrs of sound (y/n)
#'
#' @return
#' This function outputs:
#' \itemize{
#' \item Summary tables
#'  \itemize{
#'  \item Hourly summary tables include:
#'    \itemize{
#'    \item Site
#'    \item Date
#'    \item File Name
#'    \item Hour
#'    \item Deployment Number
#'    \item Sum Events
#'    \item Latitude
#'    \item Longitude
#'    \item Vegetation Class (if provided in sites file)
#'    \item Strata (if provided in sites file)
#'    \item Month
#'    \item Year
#'    \item WeekDate
#'    \item DayNight: If the hour is considered day (06:00 – 18:00) or night (18:00 – 06:00)
#'    }
#'  \item Daily summary tables include:
#'    \itemize{
#'    \item Date
#'    \item Site
#'    \item WeekDate
#'    \item Latitude
#'    \item Longitude
#'    \item Vegetation Class (if provided in sites file)
#'    \item Strata (if provided in sites file)
#'    \item total_Events
#'    \item n_hours: Total hours sampled for the date
#'    \item n_valid_hours: Total valid hours sampled for the date
#'    \item night_total: Total nighttime Events for the date
#'    \item prop_night: Proportion of nighttime Events to all Events for the date
#'    \item prop_day: Proportion of daytime Events to all Events for the date
#'    \item Month
#'    \item Year
#'    \item Week
#'    }
#'  \item Weekly summary tables include:
#'    \itemize{
#'    \item WeekDate
#'    \item Site/Strata/Vegetation Class
#'    \item Latitude
#'    \item Longitude
#'    \item Vegetation Class (if provided in sites file)
#'    \item Strata (if provided in sites file)
#'    \item MeanDailyEvents: Mean number of Events per day for the week
#'    \item sdDailyEvents: Standard deviation of the number of Events per day for the week
#'    \item n: Number of sampled days included in weekly calculations
#'    \item seDailyEvents: Standard error of the number of Events per day for the week
#'    \item maxDailyEvents: Maximum number of Events per day for the week
#'    \item minDailyEvents: Minimum number of Events per day for the week
#'    \item sumEvents: Total number of Events for the week
#'    \item sumEventsNight: Total number of nighttime Events for the week
#'    \item meanEventsNight: Mean number of nighttime Events for the week
#'    \item sdEventsNight: Standard deviation of the number of nighttime Events for the week
#'    \item seEventsNight: Standard error of the number of nighttime Events for the week
#'    \item PropNightEvents: Proportion of nighttime Events to all Events for the week
#'    \item SumEventsPerDaysSampled: Total daytime Events for the week
#'    \item SumNightEventsPerDaySampled: Nighttime Events divided by number of days per week
#'    }
#'  \item Monthly summary tables include:
#'    \itemize{
#'    \item Year
#'    \item Month
#'    \item MeanDailyEvents: Mean number of Events per day for the month
#'    \item sdDailyEvents: Standard deviation of the number of Events per day for the month
#'    \item n: Number of sampled days included in monthly calculations
#'    \item seDailyEvents: Standard error of the number of Events per day for the month
#'    \item maxDailyEvents: Maximum number of Events per day for the month
#'    \item minDailyEvents: Minimum number of Events per day for the month
#'    \item sumEvents: Total number of Events for the month
#'    \item sumNightEvents: Total number of nighttime Events for the month
#'    \item meanNightEvents: Mean number of nighttime Events for the month
#'    \item proportionNightEvents: Proportion of nighttime Events to all Events for the month
#'    \item Year-Month: WeekDate
#'    }
#' }
#' \item Summary plots
#'  \itemize{
#'  \item Plots saved in "saved_plots.Rds" include:
#'    \itemize{
#'    \item total_plot: Line plot of total Events per hour per site
#'    \item night_day_plot: Box plot of total daytime and nighttime Events for all sites
#'    \item hourly_plot: Bar plot of mean Events per hour for all sites
#'    \item daily_plot_site: Line plots of total Events per date by site
#'    \item daily_plot_strata: Line plots of total Events per date by strata (if strata is provided in sites file)
#'    \item daily_plot_veg: Line plots of total Events per date by vegetation class (if vegetation class is provided in sites file)
#'    \item weekly_plot_site: Line plots of mean number of daily Events per week per site
#'    \item weekly_plot_strata: Line plots of mean number of daily Events per week per strata (if strata provided in sites file)
#'    \item weekly_plot_veg: Line plots of mean number of daily Events per week per vegetation class (if vegetation class is provided in sites file)
#'    \item monthly_plot: Line plot of mean number of daily Events per month for all sites
#'    \item monthly_plot_site: Line plots of mean number of daily Events per month by site
#'    \item monthly_plot_strata: Line plots of mean number of daily Events per month by strata (if strata is provided in sites file)
#'    \item monthly_plot_strata_overlay: Line plots from monthly_plot_strata on the same graph
#'    }
#'  }
#' }
#'
#' @export

data_summaries_function <- function(
    parent_dir,
    project_name,
    deployment_num,
    detector_name,
    event_count_column,
    selection_tables,
    zero_txt,
    sound_check_include,
    sound_checks,
    use_only_sites_provided,
    site_lat_long,
    rand_dates_needed,
    events_bad_sound_remove
  ){

  print("Running data_summaries_function...")
  og_dir <- getwd() #to reset wd at the end of the function

    graphics.off()  # close all plot devices
    gc()            # collect garbage

    if(sound_check_include == "y"){
      print("you indicated that you have a sound_check file for this script to filter out bad sounds")
    } else {print("you indicated that you DO NOT have a sound_check file for this script to filter out bad sounds")
        }
    if(rand_dates_needed == "y"){
      print("you indicated that you would like to filter the selections by those that fall on a pre-selected random date")
    } else { print("you indicated that you DO NOT want to filter the selections by those that fall on a pre-selected random date. All dates will be included in results")
      }
    if(events_bad_sound_remove == "y"){
      print("you want to remove detections that occur on sound files with <23 hrs of sound")
    } else {print("you DO NOT want to remove detections that occur on sound files with <23 hrs of sound. Detections that occur on partial sound dates will be included in results")
        }
    if(use_only_sites_provided == "y"){
      print("you only want to include the sites that were listed in the site_lat_long file. This might result in detections being excluded if they occur on sites not included in the site_lat_long file")
    } else {print("you want to include all sites that are in the merged selection tables, and will not filter only by sites listed in the site_lat_long file.")
        }

  setwd(paste0(parent_dir, "/data_summaries"))

    # install and load necessary packages
    det_sum_packages <- c("shiny","dplyr", "tidyverse","stringr","purrr","lubridate","readxl","stargazer","broom","ggplot2")
      options(warn = -1)
    for (i in det_sum_packages){
      if (!require(i, quietly = TRUE, character.only = TRUE)){
        install.packages(i)
        library(i, character.only = TRUE)
      }
    }

   # Define helper to not kill function if saving fails
    safe_ggsave <- function(filename, plot, ...) {
      tryCatch(
        ggsave(filename, plot = plot, ...),
        error = function(e) {
          warning("ggsave failed for ", filename, ": ", conditionMessage(e))
        }
      )
    }

    normalize_detection_table <- function(table, event_count_column, file_path = NA_character_) {
      if (!(event_count_column %in% names(table))) {
        stop(
          "Selection table lacks the selected event-count column '",
          event_count_column,
          "': ",
          file_path
        )
      }
      if (event_count_column != "Count") {
        names(table)[names(table) == event_count_column] <- "Count"
      }
      table$Count <- as.numeric(table$Count)
      table$`File Offset (s)` <- as.numeric(table$`File Offset (s)`)
      table
    }

    # Make any error drop us into seeing where it came from
    options(error = rlang::entrace)  # requires rlang


  # file names
  proj_dep_name <-paste(project_name,"_dep",deployment_num,"_",detector_name,sep="") #default raw output table name

  #### LOAD IN ALL DATA ####

  ##### Sound Check Files #####
    # Should read in excel tables, not .txt files since those aren't frequently updated
    if(sound_check_include == "y"){
      sound_check_list <- list.files(path = sound_checks,
                                     recursive=T,
                                     full.names=TRUE,
                                     pattern = "*.xlsx") # list all the selection tables in the selection_tables folder
      #sound_check_list <- lapply(sound_check_list, function(x) {read.table(file = x, header = T, sep ="\t", check.names=FALSE,quote = "\"",comment.char = "")})  # Read the files in, assuming tab separator
      #sound_check_list <- rapply(sound_check_list, as.character, how = "replace") #make all columns character types before merging
      #sound_check_merge_df <- do.call("rbind", lapply(sound_check_list_df, as.data.frame)) # Combine them (the events cross over between sites and cuts off the last site - use the rbind.fill function)
      # sum(sapply(all_txt_df, nrow))
      sound_check_list_df <- lapply(sound_check_list, read_xlsx,
                                    sheet = "Sounds",
                                    col_names = TRUE)  # Read the files in
      sound_check_list_df <- lapply(sound_check_list_df, function(df) {
        if("SampleRate" %in% names(df)) {
          df$SampleRate <- as.numeric(as.character(df$SampleRate))
        }
        if ("Deployment Number" %in% names(df)) {
          df$`Deployment Number` <- as.numeric(as.character(df$`Deployment Number`))
        }
        return(df)
      })
      sound_check_merge_df <- dplyr::bind_rows(sound_check_list_df) # merge all sound check files together
      cols.nums <- c("Duration Hours",'File Duration (s)',"SampleRate")
      sound_check_merge_df[cols.nums] <- sapply(sound_check_merge_df[cols.nums],as.numeric) # set specific columns as numeric
      sound_check_merge_df$`File Start DateTime` <- as.POSIXct(str_extract(sound_check_merge_df$`Current File Name`,"\\d{8}.\\d{6}"),format='%Y%m%d_%H%M%S',origin = "1970-01-01",tz="Africa/Brazzaville") # convert the data and time charaters to real date and time with the correct time zone
      sound_check_merge_df$`File Start Date` <- format(as.Date(str_extract(sound_check_merge_df$'Current File Name' ,"\\d{8}.\\d{6}"),"%Y%m%d"),"%m/%d/%Y")
      sound_check_merge_df$`File End DateTime` <- sound_check_merge_df$`File Start DateTime`+ sound_check_merge_df$`File Duration (s)`
      sound_check_merge_df$`File End Date` <- format(as.Date(sound_check_merge_df$`File End DateTime`,"%Y%m%d",tz="Africa/Brazzaville"),"%m/%d/%Y")
      sound_check_merge_df$Detector <- "Sound Check"
      sound_check_merge_df$'Sound Check Count' <- "sound check"
      sound_check_merge_df <-dplyr::rename(sound_check_merge_df,`File Name` = `Current File Name`) # rename to, from
      #sound_check_merge_df <-rename(sound_check_merge_df,`Deployment Number` = `Deployment`) # rename to, from
      # Check if "Deployment" exists and "Deployment Number" doesn't
      if ("Deployment" %in% names(sound_check_merge_df) &&
          !("Deployment Number" %in% names(sound_check_merge_df))) {
        sound_check_merge_df <- dplyr::rename(sound_check_merge_df,
                                       `Deployment Number` = `Deployment`)
      }
      sound_check_merge_df$`Deployment Number` <- as.numeric(sound_check_merge_df$`Deployment Number`)
      sound_check_merge_df2 <- sound_check_merge_df[,c("Site", "File Name","File Duration (s)","File Start DateTime","File Start Date","File End DateTime",
                                                       "File End Date","Sound Check Count","Exclude (y/e)","Notes",
                                                       "Deployment Number")] # create new dataframe with specific columns
      sound_check_merge_df2 <- dplyr::rename(sound_check_merge_df2, "Date" = "File Start Date")
      sound_check_merge_df2$`File Start DateTime` <- as.POSIXct(str_extract(sound_check_merge_df2$'File Name',"\\d{8}.\\d{6}"),format='%Y%m%d_%H%M%S',origin = "1970-01-01",tz="Africa/Brazzaville") # convert the data and time charaters to real date and time with the correct time zone
      sound_check_merge_df2$`File Start Date` <- format(as.Date(str_extract(sound_check_merge_df2$'File Name' ,"\\d{8}.\\d{6}"),"%Y%m%d"),"%m/%d/%Y")
      sound_check_merge_df2$`File End DateTime` <- sound_check_merge_df2$`File Start DateTime`+ sound_check_merge_df2$`File Duration (s)`
      sound_check_merge_df2$`File End Date` <- format(as.Date(sound_check_merge_df2$`File End DateTime`,"%Y%m%d",tz="Africa/Brazzaville"),"%m/%d/%Y")
      sound_check_merge_df2$Hour <- hour(sound_check_merge_df2$`File Start DateTime`)
      sound_check_merge_df2$Date <- as.Date(sound_check_merge_df$`File Start Date`,format="%m/%d/%Y")
      sound_check_merge_df2$`Sound Check File` <-
      #View(sound_check_merge_df2)
      #names(sound_check_merge_df2)
      #dim(sound_check_merge_df2)
      #str(sound_check_merge_df2)
      #unique(sound_check_merge_df2$`Exclude (y/e)`, na.rm=T)
      write.table(sound_check_merge_df2,paste(parent_dir,"/data_summaries/summary_tables/",proj_dep_name,"_soundCheck_merged.txt",sep=""),sep='\t',na="",col.names=TRUE,row.names=FALSE, quote=FALSE, append=FALSE)
      print(paste("Minimum Sound Check Date",min(sound_check_merge_df2$'File Start DateTime', na.rm = TRUE),sep=" ")) # 2017-10-02 WAT
      print(paste("Maximum Sound Check Date",max(sound_check_merge_df2$'File Start DateTime', na.rm = TRUE),sep = " ")) # 2023-11-27 WAT
      print(paste("Total hours of sounds in this dataset:",round(sum(sound_check_merge_df2$`File Duration (s)`, na.rm=TRUE)/60/60, digits = 4),sep= " "))
      print(paste("Total years of sounds in this dataset:",round(sum(sound_check_merge_df2$`File Duration (s)`, na.rm=TRUE)/60/60/24/365, digits = 4),sep= " "))
    }


  ##### Rand Dates  #####
    #(3 random dates per week for event data, beginning in deployment 4)
    if(rand_dates_needed == "y"){
      elp_rand<-read.table(paste(parent_dir, '/rand-days/Rand_dates.csv', sep=""),header=TRUE,sep="\t",row.names=NULL) #read in rand file that contains 3 random days per week of the survey
      elp_rand$Date<-format(as.Date(elp_rand$Date,"%d-%b-%y"), "%m/%d/%Y") #tell R what the date structure is and read it as date and format the date to match Raven selection tables
      elp_rand$Date <- as.Date(elp_rand$Date,"%m/%d/%Y")
      elp_rand$"Rand"<-"rand" #create a column that is populated with "rand" to merge with the selection tables
    }

  ##### Selection Tables #####
  # (event detections (0+))
  selection_tables_list<-list.files(path = selection_tables,recursive=F,full.names=TRUE, pattern = "*.txt") # list all the selection tables in the selection_tables folder
  selection_tables_list <- lapply(selection_tables_list, function(x) {
    normalize_detection_table(
      read.table(file = x, header = T, sep ="\t", check.names=FALSE,quote = "\"",comment.char = "", fill=T),
      event_count_column = event_count_column,
      file_path = x
    )})  # Read and normalize the files
  #names(selection_tables_list) <- basename(selection_tables[c(1:6,8)]) # name the objects in list as the file names
  selection_tables_list <- rapply(selection_tables_list, as.character, how = "replace") #make all columns character types before merging
  events_merge_df <- dplyr::bind_rows(selection_tables_list) # merge all tables together
  #list2env(selection_tables_list ,.GlobalEnv)
  #names(events_merge_df)
  cols.num <- c("Count","Deployment Number",'File Offset (s)')
  events_merge_df[cols.num] <- lapply(events_merge_df[cols.num],as.numeric)
  events_merge_df$Site <- substr(str_match(events_merge_df$`Begin File`,"[a-zA-Z]{2}\\d{2}[a-zA-Z]{1}.")[,1],1,
                              nchar(str_match(events_merge_df$`Begin File`,"[a-zA-Z]{2}\\d{2}[a-zA-Z]{1}.")[,1])-1)
  #stem(as.numeric(events_merge_df$`Begin Hour`))
  #unique(events_merge_df$`Begin Hour`)

  events_dets_df <- events_merge_df[,c("Site", "Begin File","File Offset (s)","Count","Deployment Number","Sound Problems", "Notes")]
  events_dets_df$`File Start DateTime` <- as.POSIXct(str_extract(events_dets_df$`Begin File`,"\\d{8}.\\d{6}"),format='%Y%m%d_%H%M%S',origin = "1970-01-01",tz="Africa/Brazzaville") # convert the data and time charaters to real date and time with the correct time zone
  events_dets_df$`File Start Date` <- format(as.Date(str_extract(events_dets_df$'Begin File' ,"\\d{8}.\\d{6}"),"%Y%m%d"),"%m/%d/%Y")
  events_dets_df$`Detection DateTime` <- events_dets_df$`File Start DateTime`+ events_dets_df$`File Offset (s)`
  events_dets_df$`Date` <- as.Date(events_dets_df$`Detection DateTime`,"%Y%m%d",tz="Africa/Brazzaville")
  events_dets_df$Hour <- hour(events_dets_df$`Detection DateTime`)#format(as.POSIXct(events_dets_df$`Detection DateTime`), format = "%H") # get hour of selection
  events_dets_df$Detector <- detector_name
  events_dets_df <- dplyr::rename(events_dets_df, "File Name" = "Begin File")
  events_dets_df$Month <- month(events_dets_df$Date)
  events_dets_df$Year <- year(events_dets_df$Date)

  # View(events_dets_df)
  # dim(events_dets_df) #31854      13
  # stem(events_dets_df$Hour)
  # unique(events_dets_df$Hour)
  # names(events_dets_df)
  print(paste("Minimum Event selection table date:",min(events_dets_df$`File Start DateTime`, na.rm = TRUE),sep=" "))
  print(paste("Maximum Event selection table date:",max(events_dets_df$`File Start DateTime`, na.rm = TRUE),sep=" "))
  print(paste("Total detected Events:",sum(events_dets_df$Count, na.rm = TRUE),sep=" ")) # 2382 Events
  write.table(events_dets_df,paste(parent_dir,"/data_summaries/summary_tables/",proj_dep_name,"_events_SSTs_merged.txt",sep=""),sep='\t',na="",col.names=TRUE,row.names=FALSE, quote=FALSE, append=FALSE)


  ##### Zero-Days Tables  #####
  # selection tables with 0 hori-harm detections at filtered score threshold on rand dates
    if(exists(zero_txt)){
      zero_days<-list.files(path = zero_txt,recursive=T,full.names=TRUE, pattern = "*.txt") # list all the selection tables in the selection_tables folder
      zero_days_list <- lapply(zero_days, function(x) {
        normalize_detection_table(
          read.table(file = x, header = T, sep ="\t", check.names=FALSE,quote = "\"",comment.char = ""),
          event_count_column = event_count_column,
          file_path = x
        )})  # Read and normalize zero-day tables
      names(zero_days_list) <- basename(zero_days) # name the objects in list as the file names
      zero_days_df <- dplyr::bind_rows(zero_days_list) # merge all tables together
      zero_days_df$Rand <- ""
      #zero_days_df<- rename(zero_days_df, "Deployment Number" = "Deployment")
      #View(zero_days_df)
      #names(zero_days_df)

      zero_days_df2 <- zero_days_df[,c("Site", "Begin File","File Offset (s)","Count",
                                       "Deployment Number","Sound Problems", "Notes", "Rand")]
      #zero_days_df2 <- dplyr::rename(zero_days_df2, "Event Count" = "Count")
      zero_days_df2 <- dplyr::rename(zero_days_df2, "File Name" = "Begin File")
      zero_days_df2$'Count' <- 0
      zero_days_df2$`File Start DateTime` <- as.POSIXct(str_extract(zero_days_df2$`File Name`,"\\d{8}.\\d{6}"),format='%Y%m%d_%H%M%S',origin = "1970-01-01",tz="Africa/Brazzaville") # convert the data and time charaters to real date and time with the correct time zone
      zero_days_df2$`File Start Date` <- format(as.Date(str_extract(zero_days_df2$'File Name' ,"\\d{8}.\\d{6}"),"%Y%m%d"),"%m/%d/%Y")
      zero_days_df2$`Detection DateTime` <- zero_days_df2$`File Start DateTime`+ zero_days_df2$`File Offset (s)`
      zero_days_df2$`Date` <- as.Date(zero_days_df2$`Detection DateTime`,"%Y%m%d",tz="Africa/Brazzaville")
      zero_days_df2$`Hour` <- hour(zero_days_df2$`File Start DateTime`)
      zero_days_df2$Detector <- detector_name
    }

  #### Site information ####
    if(exists("site_lat_long")){
      site_info_names <- names(site_lat_long)
    }

  #### FILTER BY ANALYSIS DATES ####

  #create table for every hour from the first to last in detector files
  # combing events and zero days
    if(exists(zero_txt)){
      events_dets_df_zero <- full_join(events_dets_df,zero_days_df2)
      print(paste("Total Events in merged table:",sum(events_dets_df_zero$Count,na.rm=T), sep = " ")) # 2382
      print(paste("Min date in merged table:",min(events_dets_df_zero$Date), sep = " "))
      print(paste("Max date in merged table:",max(events_dets_df_zero$Date), sep = " "))
    } else {
      events_dets_df_zero <- events_dets_df
    }
  # stem(events_dets_df_zero$Hour)
  # events_dets_df_zero$Month <- month(events_dets_df_zero$Date)
  # events_dets_df_zero$Year <- year(events_dets_df_zero$Date)


  # add sound check (if user requested)
    if(events_bad_sound_remove == "y"| sound_check_include == "y"){
           events_dets_df_zero <- full_join(events_dets_df_zero,sound_check_merge_df2) # merge det df with sound check
           events_dets_df_zero <- events_dets_df_zero %>%
             filter(is.na(`Exclude (y/e)`) | !(`Exclude (y/e)` %in% c("y", "Y","e")))
          }
  # sum(events_dets_df_zero$`Event Count`, na.rm = T)
  # unique(events_dets_df_zero$`Exclude (y/e)`,na.rm=T)

  # add rand dates (if user requested) and remove detections on non rand dates if requested
  # Note: For Deployments 2-3, 3 random dates were selected to be consistent with the other deployments (dep 01 is missing)
    if(rand_dates_needed == "y"){
          #events_dets_df_zero <- events_dets_df_zero[,-14] # WHY IS THE  14TH COLUMN REMOVED HERE?
          events_dets_df_zero <- left_join(events_dets_df_zero,elp_rand, by = "Date") # combine rand dates with Event table
          events_dets_df_zero <- events_dets_df_zero %>% filter(`Rand` == "rand")# remove nonRand dates
    }
    events_dets_df_zero <- events_dets_df_zero %>%
      mutate(
        `Count` = as.numeric(`Count`)
      )
  # unique(events_dets_df_zero$Rand)
  # sum(events_dets_df_zero$`Event Count`, na.rm = T)
  # names(events_dets_df_zero)
  # zero_days_df2 %>% filter(Date == "2021-06-05", Site == "nn03g") %>%  nrow() > 0 # check for unintended dates


  #### HOURLY SUMMARIES ####
  # summarize Event count to hourly
    events_dets_df_zero_hr <- events_dets_df_zero %>%
      # Group by these variables
      dplyr::group_by(Date, Hour, Site, `Deployment Number`,`File Name`) %>%
      # Summarize Event Count for each group
      dplyr::summarise(
        "Sum Events" = if(all(is.na(`Count`))) {
          NA_real_  # If all values in group are NA, keep it NA
        } else {
          sum(`Count`, na.rm = TRUE)  # Otherwise sum non-NA values
        }
      ) %>%
      ungroup()
    print(paste("Total Events in merged hourly table:",sum(events_dets_df_zero_hr$`Sum Events`, na.rm=T),sep = " ")) # 57339
    #dim(events_dets_df_zero_hr) #45051      4
    min(events_dets_df_zero_hr$Date)
    max(events_dets_df_zero_hr$Date)


  ## hourly summary Events ##
  # get unique date/sites from detection df
    events_date_site <- events_dets_df_zero_hr[,c(-2,-4,-6)]
    events_date_site <- events_date_site %>%
      select(Site, Date, `File Name`) %>%
      distinct()
    #dim(events_date_site)

  # Create a complete hour sequence for each surveyed Site-Date combination (so every hour sampled is represented, which they are missing from the SST)
    events_date_site_hr <- events_date_site %>%
      mutate(Hour = list(0:23)) %>%
      unnest(Hour)

  # merge the hourly dets df with the hourly df
    events_hrly1 <- left_join(events_date_site_hr,events_dets_df_zero_hr, by = c("Site", "Date", "Hour","File Name"))
    events_hrly1$`Sum Events`[is.na(events_hrly1$`Sum Events`)] <- 0
    # events_hrly1$Month <- month(events_hrly1$Date)
    # events_hrly1$Year <- year(events_hrly1$Date)
    print(paste("Total Events in merged hourly table: ",sum(events_hrly1$`Sum Events`, na.rm=T),sep = ""))
    #unique(events_hrly$Hour)

  # merge with gunshots data (needs development)
  # merge with bad sound quality times (needs to be determined by noise levels) - should be incorporated in the sound check file instead!

  # add strata, lat, and long information from the sites txt file
    if(exists("site_lat_long")){
      events_hrly <- full_join(events_hrly1,site_lat_long)
    } else {
      events_hrly <- events_hrly1
    }
    events_hrly$Month <- month(events_hrly$Date)
    events_hrly$Year <- year(events_hrly$Date)
    events_hrly$`Sum Events`<- as.numeric(events_hrly$`Sum Events`)

  # day vs night
    #library(suncalc)
      # use lat long of each site to determine daily day and night hours
  events_hrly$DayNight<-ifelse(events_hrly$Hour<6,"Night",
                          ifelse(events_hrly$Hour<18,"Day","Night"))
  #events_hrly$JulianWeek <- round(julian(events_hrly$Date)/7,digits=0)# add week of the dataset
  events_hrly$WeekDate <- floor_date(events_hrly$Date, 'week') + 1 #first date of the week

  # remove any sites that aren't in the user provided Site list (e.g., cluster analysis sites (nn09c1, nn09c2, nn09c3, nn09c4, etc))
  if(use_only_sites_provided == "y"){
    events_hrly <- events_hrly[(events_hrly$Site %in% unique(site_lat_long$Site)),]
  }
  #unique(events_hrly$Site)
  #sum(events_hrly$`Sum Events`,na.rm=T) #36236

  write.table(events_hrly,paste(parent_dir,"/data_summaries/summary_tables/",proj_dep_name,"_Events_ZeroDays_ExcludeBadSounds_Rand_hourly.txt",sep=""),
             sep='\t',na="",col.names=TRUE,row.names=FALSE, quote=FALSE, append=FALSE)

  nightEvents <- sum(events_hrly$`Sum Events`[events_hrly$DayNight == "Night"],na.rm=TRUE)  #38791
  dayEvents <- sum(events_hrly$`Sum Events`[events_hrly$DayNight == "Day"],na.rm=TRUE) #2246
  proportionNightEvents <- nightEvents/(nightEvents+dayEvents) #0.945
  print(paste("Proportion of night-time Events: ",round(proportionNightEvents,digits=3),sep=" "))

  ## plot hourly data
  ##### total Events per date by site #####
  events_hrly_Date_plot<- ggplot(as.data.frame(events_hrly), aes(x = Date, y = `Sum Events`)) +
                          geom_line(na.rm=FALSE) +
                          theme_bw() +
                          #facet_wrap(~Site)+
                          labs(title="Total Events per Hour")

  ##### Events day vs night #####
  events_hrly_nightday_plot <- ggplot(as.data.frame(events_hrly), aes(x = DayNight, y = `Sum Events`)) +
                                geom_boxplot() +
                                theme_bw()+
                            labs(title="Total Events per Day and Night")

  ##### Events per hour (improve axis) #####
  events_hr_plot<- ggplot(as.data.frame(events_hrly), aes(x = Hour, y = `Sum Events`)) +
                    stat_summary(fun = mean, geom = "bar") +
                    stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2) +
                    theme_bw()+
                    labs(title = "Mean Events Per Hour",
                         y = "Mean Events (±SE)",
                         x = "Hour")


  #### DAILY SUMMARIES ####
  # summarize daily Events from hourly table
  daily_site_summary <- events_hrly %>%
    dplyr::group_by(Date, Site, WeekDate, across(all_of(site_info_names))) %>%
    dplyr::summarise(
      total_Events = if(sum(!is.na(`Sum Events`)) == 0) NA_real_  # If all values are NA
      else sum(`Sum Events`, na.rm = TRUE),
      n_hours = dplyr::n(),
      n_valid_hours = sum(!is.na(`Sum Events`)),  # Count of non-NA hours
      night_total = if(sum(!is.na(`Sum Events`[DayNight == "Night"])) == 0) NA_real_
      else sum(`Sum Events`[DayNight == "Night"], na.rm = TRUE),
      .groups = 'drop'
    ) %>%
    # Calculate proportions after summarizing
    mutate(
      prop_night = night_total/total_Events,
      prop_day = (total_Events-night_total)/total_Events
    )

  daily_site_summary$Month <- month(daily_site_summary$Date)
  daily_site_summary$Year <- year(daily_site_summary$Date)
  daily_site_summary$Week <- week(daily_site_summary$Date)
  print(paste("Total Events per day for all dates:",sum(daily_site_summary$total_Events, na.rm=TRUE),sep=" ")) #36656

  write.table(daily_site_summary,
              paste(parent_dir,"/data_summaries/summary_tables/",proj_dep_name,"_Events_perDay.txt",sep=""),
              sep='\t',na="",col.names=TRUE,row.names=FALSE, quote=FALSE, append=FALSE)


  # Add all dates to the daily summary dataframe and fill them with NA so they have gaps in time in the plot
  # allows gaps in plots (if random dates enabled, then there will be many gaps)
  # create a complete sequence of dates
  # Quick validation before seq()
    date_range <- seq(min(daily_site_summary$Date, na.rm = TRUE),
                      max(daily_site_summary$Date, na.rm = TRUE),
                      by="day")
  #
  # date_range <- seq(min(daily_site_summary$Date),
  #                   max(daily_site_summary$Date),
  #                   by="day")
  # Create a data frame with all combinations of dates and strata
  complete_dates <- expand.grid(
    Date = date_range,
    Site = unique(daily_site_summary$Site))
  # Join this with your original data
  daily_site_summary_complete <- left_join(complete_dates, daily_site_summary)
  #names(daily_site_summary_complete)
  daily_site_summary_complete <- daily_site_summary_complete %>%
    mutate(
      total_Events = as.numeric(total_Events),
      night_total   = as.numeric(night_total)
    )

  ##### daily per site #####
  # Time series of total Events per site
  Events_daily_site_plot <- ggplot(as.data.frame(daily_site_summary_complete), aes(x = Date, y = total_Events)) +
    geom_line(na.rm=TRUE) +
    theme_bw() +
    facet_wrap(~Site) +
    scale_x_date(date_breaks = "6 month", date_labels = "%b-%Y")+
    theme(axis.text.x=element_text(angle=60, hjust=1),plot.title = element_text(hjust = 0.5),
          panel.grid.major = element_line(colour="white", size=0.5))+
    labs(title = "Total events per Date by Site",
         y = "Total Events",
         x = "Date")

  ##### daily per strata #####
  if("Strata" %in% names(daily_site_summary)){
    daily_strata_summary <- events_hrly %>%
      group_by(Date,`WeekDate`,Strata) %>%
      dplyr::summarise(
        total_Events = sum(`Sum Events`, na.rm = FALSE),
        n_hours = n(),
        night_total = sum(`Sum Events`[DayNight == "Night"], na.rm = FALSE),
        prop_night = night_total/total_Events,
        prop_day = (total_Events-night_total)/total_Events
      ) %>%
      ungroup()
    print(paste("Total Events per day for all dates:",sum(daily_strata_summary$total_Events, na.rm=TRUE),sep=" ")) #36656
    complete_dates2 <- expand.grid(
      Date = date_range,
      Strata = unique(daily_strata_summary$Strata))
    # Join this with your original data
    daily_strata_summary_complete <- left_join(complete_dates2, daily_strata_summary)
    Events_daily_strata_plot <- ggplot(as.data.frame(daily_strata_summary_complete), aes(x = Date, y = total_Events, group = Strata)) +
      geom_line(na.rm=TRUE) +
      theme_bw() +
      facet_wrap(~Strata) +
      scale_y_continuous(limits = c(0, NA), expand = c(0, 0)) +
      scale_x_date(date_breaks = "4 month", date_labels = "%b-%Y")+
      theme(axis.text.x=element_text(angle=60, hjust=1),plot.title = element_text(hjust = 0.5),
            panel.grid.major = element_line(colour="white", size=0.5))+
      labs(title = "Total Events per Date by Strata",
           y = "Total Events",
           x = "Date")

    # save table
    events_daily_strata_table <-  daily_site_summary %>%
      dplyr::group_by(Strata) %>%
      dplyr::summarize(
        "Total Events" = sum(total_Events,na.rm = TRUE),
        "Sum days sampled" = n(),
        "Average Events per day" = mean(total_Events, na.rm=TRUE),
        "Maximum Events per day" = max(total_Events, na.rm=TRUE),
        "Total night Events" = sum(night_total, na.rm=TRUE),
        "Average night time Events" = mean(night_total,na.rm=TRUE),
        "Maximum night Events" = max(night_total,na.rm=TRUE),
        "Proportion night time Events" = round(`Total night Events`/`Total Events`,digits = 3)) %>%
      ungroup()
    View(events_daily_strata_table)
    write.table(events_daily_strata_table,
                paste(parent_dir,"/data_summaries/summary_tables/",proj_dep_name,"_Events_perDay_perStrata.txt",sep=""),
                sep='\t',na="",col.names=TRUE,row.names=FALSE, quote=FALSE, append=FALSE)

  }

  ##### daily per vegetation class #####
  if("Vegetation Class" %in% names(daily_site_summary)){
    daily_veg_summary <- events_hrly %>%
      dplyr::group_by(Date,`WeekDate`,`Vegetation Class`) %>%
      dplyr::summarise(
        total_Events = sum(`Sum Events`, na.rm = FALSE),
        n_hours = n(),
        night_total = sum(`Sum Events`[DayNight == "Night"], na.rm = FALSE),
        prop_night = night_total/total_Events,
        prop_day = (total_Events-night_total)/total_Events
      ) %>%
      ungroup()
    print(paste("Total Events per day for all dates:",sum(daily_veg_summary$total_Events, na.rm=TRUE),sep=" ")) #36656
    complete_dates3 <- expand.grid(
      Date = date_range,
      `Vegetation Class` = unique(daily_veg_summary$`Vegetation Class`)) %>%
      arrange(`Vegetation Class`, Date)
    # Join this with your original data
    daily_veg_summary_complete <- left_join(complete_dates3, daily_veg_summary)
    #print(paste("Total Events per day for all dates:",sum(daily_veg_summary_complete$total_Events, na.rm=TRUE),sep=" ")) #36656
    Events_daily_veg_plot <- ggplot(as.data.frame(daily_veg_summary_complete), aes(x = Date, y = total_Events, group = "Vegetation Class")) +
      geom_line(na.rm=TRUE) +
      theme_bw() +
      facet_wrap(~`Vegetation Class`) +
      scale_y_continuous(limits = c(0, NA), expand = c(0, 0)) +
      scale_x_date(date_breaks = "4 month", date_labels = "%b-%Y")+
      theme(axis.text.x=element_text(angle=60, hjust=1),plot.title = element_text(hjust = 0.5),
            panel.grid.major = element_line(colour="white", size=0.5))+
      labs(title = "Total Events Per Day by Vegetation Class",
           y = "Total Events",
           x = "Date")

    write.table(daily_veg_summary_complete,
                paste(parent_dir,"/data_summaries/summary_tables/",proj_dep_name,"_Events_perDay_perVegClass.txt",sep=""),
                sep='\t',na="",col.names=TRUE,row.names=FALSE, quote=FALSE, append=FALSE)
  }


  #### WEEKLY SUMMARIES ####
  ##### weekly per site #####
  # summarize weekly presence
  Event_weekly_means_site <- daily_site_summary %>%
    dplyr::group_by(Site,WeekDate,across(all_of(site_info_names))) %>%
    dplyr::summarise(
      MeanDailyEvents = if(all(is.na(`total_Events`))) NA_real_
      else mean(`total_Events`, na.rm=TRUE),
      sdDailyEvents = if(all(is.na(`total_Events`))) NA_real_
      else sd(`total_Events`, na.rm=TRUE),
      n = dplyr::n(),
      seDailyEvents = sdDailyEvents/sqrt(n),
      maxDailyEvents = if(all(is.na(`total_Events`))) NA_real_
      else max(`total_Events`, na.rm=TRUE),
      minDailyEvents = if(all(is.na(`total_Events`))) NA_real_
      else min(`total_Events`, na.rm=TRUE),
      sumEvents = if(all(is.na(`total_Events`))) NA_real_
      else sum(`total_Events`, na.rm=TRUE),
      sumEventsNight = if(all(is.na(`night_total`))) NA_real_
      else sum(`night_total`, na.rm=TRUE),
      meanEventsNight = if(all(is.na(`night_total`))) NA_real_
      else mean(`night_total`, na.rm=TRUE),
      sdEventsNight = if(all(is.na(`night_total`))) NA_real_
      else sd(`night_total`, na.rm=TRUE),
      seEventsNight = sdEventsNight/sqrt(n),
      PropNightEvents = round(sumEventsNight/sumEvents, digit = 3),
      SumEventsPerDaysSampled = round(sumEvents/n,digit=3),
      SumNightEventsPerDaysSampled = round(sumEventsNight/n,digit=3)
    )
  #sum(Event_weekly_means_site$sumEvents, na.rm=T) #36236
  Event_weekly_means_site$PropNightEvents[is.nan(Event_weekly_means_site$PropNightEvents)] <- NA # remove NaN from proportion calc.
  #stem(Event_weekly_means_site$PropNightEvents) # look at the distribution of night Event proportions

  write.table(Event_weekly_means_site,paste(parent_dir,"/data_summaries/summary_tables/",proj_dep_name,
                                             "_Events_Site_Weekly_Summaries.txt",sep=""),
              sep='\t',na="",col.names=TRUE,row.names=FALSE,
              quote=FALSE, append=FALSE)

  # Create a complete week timeseries and identify gaps in data so they are not plotted
  week_range <- seq(min(Event_weekly_means_site$WeekDate, na.rm=TRUE), max(Event_weekly_means_site$WeekDate, na.rm = TRUE), by="7 days")
  # Create a data frame with all combinations of dates and strata
  complete_weeks <- expand.grid(
    WeekDate = week_range,
    Site = unique(Event_weekly_means_site$Site))
  # Join this with your original data
  Event_weekly_means_site_complete <- left_join(complete_weeks, Event_weekly_means_site, by = c("Site","WeekDate"))

  # plot the mean Events per day per week by site
  EventWklySite<-ggplot(as.data.frame(Event_weekly_means_site_complete), aes(x=as.Date(WeekDate),y=MeanDailyEvents))+
    geom_line(na.rm = TRUE)+
    geom_point()+
    geom_errorbar(aes(ymin = MeanDailyEvents - seDailyEvents,
                      ymax = MeanDailyEvents + seDailyEvents),
                  width = 0.2)+
    #stat_summary(fun.data=mean_cl_normal)+
    #geom_smooth(method='lm', se = TRUE, size = 1.2, linetype = "dashed", aes(color = Strata))+
    theme_bw() +
    facet_wrap(~Site)+
    scale_x_date(date_breaks = "6 month", date_labels = "%b-%Y") +
    scale_y_continuous(
      limits = c(0, max(Event_weekly_means_site_complete$MeanDailyEvents +
                          Event_weekly_means_site_complete$seDailyEvents, na.rm = TRUE)),
      breaks = seq(0, max(Event_weekly_means_site_complete$MeanDailyEvents +
                            Event_weekly_means_site_complete$seDailyEvents, na.rm = TRUE),
                   by = 50),
      minor_breaks = NULL,
      expand = c(0,0))+  # This removes the space below 0
    theme(axis.text.x=element_text(angle=60, hjust=1),plot.title = element_text(hjust = 0.5),
          panel.grid.major = element_line(colour="white", size=0.5))+
    labs(title = "Mean Daily events per Week by Site",
         x = "Week (month-year)",
         y = "Mean Daily Events per Week (±SE)")

  if(!is.null(EventWklySite$data$Strata)){
    EventWklySite <- EventWklySite +
      geom_smooth(method='lm', se = TRUE, size = 1.2, linetype = "dashed", aes(color = Strata))
  } else {
    EventWklySite <- EventWklySite +
      geom_smooth(method='lm', se = TRUE, size = 1.2, linetype = "dashed")
  }

  ##### weekly per strata #####
  # DOES NOT ALLOW FOR GAPS IN THE DATA
  if("Strata" %in% names(daily_site_summary)){
    # group by strata instead of site and get means per week
    Event_weekly_means_strata <- daily_site_summary %>%
      dplyr::group_by(Strata,WeekDate) %>%
      dplyr::summarise(
        MeanDailyEvents = if(all(is.na(`total_Events`))) NA_real_
        else mean(`total_Events`, na.rm=TRUE),
        sdDailyEvents = if(all(is.na(`total_Events`))) NA_real_
        else sd(`total_Events`, na.rm=TRUE),
        n = dplyr::n(),
        seDailyEvents = sdDailyEvents/sqrt(n),
        maxDailyEvents = if(all(is.na(`total_Events`))) NA_real_
        else max(`total_Events`, na.rm=TRUE),
        minDailyEvents = if(all(is.na(`total_Events`))) NA_real_
        else min(`total_Events`, na.rm=TRUE),
        sumEvents = if(all(is.na(`total_Events`))) NA_real_
        else sum(`total_Events`, na.rm=TRUE),
        sumEventsNight = if(all(is.na(`night_total`))) NA_real_
        else sum(`night_total`, na.rm=TRUE),
        meanEventsNight = if(all(is.na(`night_total`))) NA_real_
        else mean(`night_total`, na.rm=TRUE),
        sdEventsNight = if(all(is.na(`night_total`))) NA_real_
        else sd(`night_total`, na.rm=TRUE),
        seEventsNight = sdEventsNight/sqrt(n),
        PropNightEvents = round(sumEventsNight/sumEvents, digit = 3),
        SumEventsPerDaysSampled = round(sumEvents/n,digit=3),
        SumNightEventsPerDaysSampled = round(sumEventsNight/n,digit=3)
      )
    # combine these data with the complete list of weeks to allow for gaps in plot
    complete_weeks_strat <- expand.grid(
      WeekDate = week_range,
      Strata = unique(Event_weekly_means_strata$Strata))
    Event_weekly_means_strata_complete <- left_join(complete_weeks_strat, Event_weekly_means_strata, by = c("Strata","WeekDate"))
    #save table
    #View(Event_weekly_means_strata_complete)
    write.table(Event_weekly_means_strata_complete,paste0(parent_dir,"/data_summaries/summary_tables/",proj_dep_name,
                                                          "_Events_Strata_Weekly_Summaries.txt"),
                sep='\t',na="",col.names=TRUE,row.names=FALSE,
                quote=FALSE, append=FALSE)

    # plot
    EventWklyStrata<-ggplot(as.data.frame(Event_weekly_means_strata_complete), aes(x=as.Date(WeekDate),y=MeanDailyEvents))+
      geom_line(na.rm = TRUE)+
      geom_point()+
      geom_errorbar(aes(ymin = MeanDailyEvents - seDailyEvents,
                        ymax = MeanDailyEvents + seDailyEvents),
                    width = 0.2)+
      #stat_summary(fun.data=mean_cl_normal)+
      geom_smooth(method='lm', se = TRUE, size = 1.2, linetype = "dashed", aes(color = Strata))+
      theme_bw() +
      facet_wrap(~Strata)+
      scale_x_date(date_breaks = "6 month", date_labels = "%b-%Y") +
      scale_y_continuous(
        #name = "Mean Daily Events per Week",
        limits = c(0, max(Event_weekly_means_strata_complete$MeanDailyEvents +
                            max(Event_weekly_means_strata_complete$seDailyEvents, na.rm = TRUE), na.rm = TRUE)+5),
        breaks = seq(0, max(Event_weekly_means_strata_complete$MeanDailyEvents +
                              Event_weekly_means_strata_complete$seDailyEvents, na.rm = TRUE)+5,
                     by = 10),
        minor_breaks = NULL,
        expand = c(0,0))+  # This removes the space below 0
      theme(axis.text.x=element_text(angle=60, hjust=1),plot.title = element_text(hjust = 0.5),
            panel.grid.major = element_line(colour="white", size=0.5))+
      labs(title = "Mean Daily Events per Week by Strata",
           x = "Week (month-year)",
           y = "Mean Daily Events per Week (±SE)")

    # plot weekly mean Events with secondary weekly night mean Events axis
    EventWklyStrata_WithNight <- ggplot(as.data.frame(Event_weekly_means_strata_complete)) +
      # Primary axis elements
      geom_line(aes(x = WeekDate, y = MeanDailyEvents)) +
      geom_point(aes(x = WeekDate, y = MeanDailyEvents)) +
      geom_errorbar(aes(x = WeekDate,
                        ymin = MeanDailyEvents - seDailyEvents,
                        ymax = MeanDailyEvents + seDailyEvents),
                    width = 0.2) +
      geom_smooth(aes(x = WeekDate, y = MeanDailyEvents, color = Strata),
                  method = 'lm', se = TRUE, size = 1.2, linetype = "dashed") +
      # Secondary axis elements for night Events
      geom_line(aes(x = WeekDate, y = meanEventsNight),
                color = "red", linetype = "dotted") +
      geom_point(aes(x = WeekDate, y = meanEventsNight),
                 color = "red") +
      # Facets and themes
      facet_wrap(~Strata) +
      theme_bw() +
      # Axis formatting
      scale_x_date(date_breaks = "6 month", date_labels = "%b-%Y") +
      scale_y_continuous(
        name = "Mean Daily Events per Week (±SE)",
        limits = c(0, max(Event_weekly_means_strata_complete$MeanDailyEvents +
                            Event_weekly_means_strata_complete$seDailyEvents, na.rm = TRUE)+5),
        breaks = seq(0, max(Event_weekly_means_strata_complete$MeanDailyEvents +
                              Event_weekly_means_strata_complete$seDailyEvents, na.rm = TRUE)+5,
                     by = 10),  # Adjust this value to change break frequency
        expand = c(0,0),
        sec.axis = sec_axis(~.,
                            name = "Mean Night Events per Week (±SE)",
                            breaks = seq(0, max(Event_weekly_means_strata_complete$MeanDailyEvents +
                                                  Event_weekly_means_strata_complete$seDailyEvents, na.rm = TRUE)+5,
                                         by = 10))  # Adjust this value to match primary axis
      ) +
      # Theme elements
      theme(axis.text.x = element_text(angle = 60, hjust = 1),
            plot.title = element_text(hjust = 0.5),
            panel.grid.major = element_line(colour = "gray90"),  # Lighter grid lines
            panel.grid.minor = element_blank(),
            axis.title.y.right = element_text(color = "red"),
            axis.text.y.right = element_text(color = "red")) +
      # Labels
      labs(title = "Mean Daily Events per Week by Strata",
           x = "Week (month-year)",
           color = "Strata")
  }

  ##### weekly per Vegetation Class #####
  # WORKING ON THIS - Mean daily (per site) rather than weekly across all sites is better
  # zero introduced on non-sampled dates?
  if("Vegetation Class" %in% names(daily_site_summary)){
    # group by strata instead of site and get means per week
    Event_weekly_means_veg <- daily_site_summary %>%
      dplyr::group_by(`Vegetation Class`,WeekDate) %>%
      dplyr::summarise(
        MeanDailyEvents = if(all(is.na(`total_Events`))) NA_real_
        else mean(`total_Events`, na.rm=TRUE),
        sdDailyEvents = if(all(is.na(`total_Events`))) NA_real_
        else sd(`total_Events`, na.rm=TRUE),
        n = dplyr::n(),
        seDailyEvents = sdDailyEvents/sqrt(n),
        maxDailyEvents = if(all(is.na(`total_Events`))) NA_real_
        else max(`total_Events`, na.rm=TRUE),
        minDailyEvents = if(all(is.na(`total_Events`))) NA_real_
        else min(`total_Events`, na.rm=TRUE),
        sumEvents = if(all(is.na(`total_Events`))) NA_real_
        else sum(`total_Events`, na.rm=TRUE),
        sumEventsNight = if(all(is.na(`night_total`))) NA_real_
        else sum(`night_total`, na.rm=TRUE),
        meanEventsNight = if(all(is.na(`night_total`))) NA_real_
        else mean(`night_total`, na.rm=TRUE),
        sdEventsNight = if(all(is.na(`night_total`))) NA_real_
        else sd(`night_total`, na.rm=TRUE),
        seEventsNight = sdEventsNight/sqrt(n),
        PropNightEvents = round(sumEventsNight/sumEvents, digit = 3),
        SumEventsPerDaysSampled = round(sumEvents/n,digit=3),
        SumNightEventsPerDaysSampled = round(sumEventsNight/n,digit=3)
      )
    # combine with complete weeks
    complete_weeks_veg <- expand.grid(
      WeekDate = week_range,
      `Vegetation Class` = unique(Event_weekly_means_veg$`Vegetation Class`))
    Event_weekly_means_veg_complete <- left_join(complete_weeks_veg, Event_weekly_means_veg, by = c("Vegetation Class","WeekDate"))

    # plot
    EventWklyVeg<-ggplot(as.data.frame(Event_weekly_means_veg_complete), aes(x=as.Date(WeekDate),y=MeanDailyEvents))+
      geom_line(na.rm = TRUE)+
      geom_point()+
      geom_errorbar(aes(ymin = MeanDailyEvents - seDailyEvents,
                        ymax = MeanDailyEvents + seDailyEvents),
                    width = 0.2)+
      #stat_summary(fun.data=mean_cl_normal)+
      geom_smooth(method='lm', se = TRUE, size = 1.2, linetype = "dashed", aes(color = `Vegetation Class`))+
      theme_bw() +
      facet_wrap(~`Vegetation Class`)+
      scale_x_date(date_breaks = "6 month", date_labels = "%b-%Y") +
      scale_y_continuous(
        #name = "Mean Daily Events per Week",
        limits = c(0, max(Event_weekly_means_veg_complete$MeanDailyEvents +
                            max(Event_weekly_means_veg_complete$seDailyEvents, na.rm = TRUE), na.rm = TRUE)+5),
        breaks = seq(0, max(Event_weekly_means_veg_complete$MeanDailyEvents +
                              Event_weekly_means_veg_complete$seDailyEvents, na.rm = TRUE)+5,
                     by = 50),
        minor_breaks = NULL,
        expand = c(0,0))+  # This removes the space below 0
      theme(axis.text.x=element_text(angle=60, hjust=1),plot.title = element_text(hjust = 0.5),
            panel.grid.major = element_line(colour="white", size=0.5))+
      labs(title = "Mean Daily Events per Week by Vegetation Class",
           x = "Week (month-year)",
           y = "Mean Daily Events per Week (±SE)")

    write.table(Event_weekly_means_veg_complete,paste0(parent_dir,"/data_summaries/summary_tables/",proj_dep_name,
                                                       "_Mean_Daily_Events_VegClass_Weekly_Summaries.txt"),
                sep='\t',na="",col.names=TRUE,row.names=FALSE,
                quote=FALSE, append=FALSE)
  }


  #### MONTHLY SUMMARIES ####
  # add number of days sampled per month
  # add number of Events per sampled date value
  # plot proportion of night Events per month

  ##### mean daily per month by site #####
  Event_monthly_means_site <- daily_site_summary %>%
    dplyr::group_by(Year,Month,Site) %>%
    dplyr::summarise(
      MeanDailyEvents = if(all(is.na(total_Events))) NA_real_
      else mean(total_Events, na.rm=TRUE),
      sdDailyEvents = if(all(is.na(total_Events))) NA_real_
      else sd(total_Events, na.rm=TRUE),
      n = n(),
      seDailyEvents = sdDailyEvents/sqrt(n),
      maxDailyEvents = if(all(is.na(total_Events))) NA_real_
      else max(total_Events, na.rm=TRUE),
      minDailyEvents = if(all(is.na(total_Events))) NA_real_
      else min(total_Events, na.rm=TRUE),
      sumEvents = if(all(is.na(total_Events))) NA_real_
      else sum(total_Events, na.rm=TRUE),
      sumNightEvents = if(all(is.na(night_total))) NA_real_
      else sum(night_total,na.rm=TRUE),
      meanNightEvents = if(all(is.na(night_total))) NA_real_
      else mean(night_total,na.rm=TRUE),
      proportionNightEvents = sumNightEvents/sumEvents
    )
  sum(Event_monthly_means_site$sumEvents, na.rm=T) #36236
  Event_monthly_means_site$`Year-Month` <- as.Date(paste(Event_monthly_means_site$Year, Event_monthly_means_site$Month, "01", sep = "-"))
  # create a grouping variable for consecutive months
  Event_monthly_means_site <- Event_monthly_means_site %>%
    arrange(Site, `Year-Month`) %>%
    dplyr::group_by(Site) %>%
    mutate(month_group = cumsum(c(TRUE, diff(as.numeric(`Year-Month`)) > 31))) %>%
    ungroup()
  write.table(Event_monthly_means_site,
              paste0(parent_dir,"/data_summaries/summary_tables/",proj_dep_name,"_Events_ZeroDays_soundExcluded_3randDaysOnly_MonthlyMean_Site.txt"),
              sep='\t',na="",col.names=TRUE,row.names=FALSE, quote=FALSE, append=FALSE)

  # plot monthly means by site
  Event_monthly_means_site_plot <- ggplot(as.data.frame(Event_monthly_means_site),aes(x=`Year-Month`,y=MeanDailyEvents))+
    geom_line(aes(group = month_group))+
    #geom_point()+
    stat_summary(fun.data=mean_cl_normal)+
    facet_wrap(~Site)+
    scale_x_date(date_breaks = "6 months",
                 date_labels = "%b-%Y")+
    scale_y_continuous(trans = "pseudo_log")+
    theme(axis.text.x = element_text(angle = 60, hjust = 1),
          plot.title = element_text(hjust = 0.5),
          panel.grid.major = element_line(colour = "white"),
          panel.grid.minor = element_blank())+
    labs(title = "Average Number of Events per Day per Month by Site",
         x = "Date (Month-Year)",
         y = "Log-Transformed Average Number of Events per Day (+/- SE)")

  ##### average Events per day by month #####
  Event_monthly_means <- daily_site_summary %>%
    dplyr::group_by(Year,Month) %>%
    dplyr::summarise(
      MeanDailyEvents = if(all(is.na(total_Events))) NA_real_
      else mean(total_Events, na.rm=TRUE),
      sdDailyEvents = if(all(is.na(total_Events))) NA_real_
      else sd(total_Events, na.rm=TRUE),
      n = n(),
      seDailyEvents = sdDailyEvents/sqrt(n),
      maxDailyEvents = if(all(is.na(total_Events))) NA_real_
      else max(total_Events, na.rm=TRUE),
      minDailyEvents = if(all(is.na(total_Events))) NA_real_
      else min(total_Events, na.rm=TRUE),
      sumEvents = if(all(is.na(total_Events))) NA_real_
      else sum(total_Events, na.rm=TRUE),
      sumNightEvents = if(all(is.na(night_total))) NA_real_
      else sum(night_total,na.rm=TRUE),
      meanNightEvents = if(all(is.na(night_total))) NA_real_
      else mean(night_total,na.rm=TRUE),
      proportionNightEvents = sumNightEvents/sumEvents
    )
  sum(Event_monthly_means$sumEvents, na.rm=T) #36236
  Event_monthly_means$`Year-Month` <- as.Date(paste(Event_monthly_means$Year, Event_monthly_means$Month, "01", sep = "-"))
  write.table(Event_monthly_means,
              paste0(parent_dir,"/data_summaries/summary_tables/",proj_dep_name,"_Events_ZeroDays_soundExcluded_3randDaysOnly_MonthlyMean.txt"),
              sep='\t',na="",col.names=TRUE,row.names=FALSE, quote=FALSE, append=FALSE)

  # Create complete time series
  all_dates <- seq.Date(
    from = min(Event_monthly_means$`Year-Month`, na.rm = TRUE),
    to = max(Event_monthly_means$`Year-Month`, na.rm = TRUE),
    by = "1 month"
  )
  # Create complete dataset with all months
  monthly_means_complete <- tibble(`Year-Month` = all_dates) %>%
    left_join(Event_monthly_means, by = "Year-Month")
  # add days since start to table for lm
  monthly_means_complete <- monthly_means_complete %>%
    mutate(days_since_start = as.numeric(`Year-Month` - min(`Year-Month`)))
  # plot monthly means
  Event_monthly_means_plot <- ggplot() +
    geom_errorbar(data = monthly_means_complete,
                  aes(x = `Year-Month`,
                      ymin = MeanDailyEvents - seDailyEvents,
                      ymax = MeanDailyEvents + seDailyEvents),
                  width = 10,
                  size = 0.5,
                  alpha = 0.7) +
    geom_line(data = monthly_means_complete,
              aes(x = `Year-Month`, y = MeanDailyEvents),
              alpha = 0.5) +
    geom_point(data = monthly_means_complete,
               aes(x = `Year-Month`, y = MeanDailyEvents),
               color = "blue",
               size = 2) +
    geom_smooth(data = monthly_means_complete,
                aes(x = `Year-Month`, y = MeanDailyEvents),
                method = "lm",
                se = TRUE,
                color = "blue") +
    scale_x_date(date_breaks = "6 months",
                 date_labels = "%b-%Y") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 60, hjust = 1),
          plot.title = element_text(hjust = 0.5),
          panel.grid.major = element_line(colour = "gray90"),
          panel.grid.minor = element_blank()) +
    labs(title = "Average Daily Events per Month",
         subtitle = "Blue points show monthly averages (± SE)",
         x = "Month-Year",
         y = "Average Daily Events (± SE)")

  # Fit the linear model for monthly means
  lm_fit <- lm(MeanDailyEvents ~ days_since_start, data = monthly_means_complete)
  print(cat("Monthly Means Linear Regression Summary:\n"))
  print(summary(lm_fit))
  stargazer(lm_fit,
            type = "text",
            title = "Monthly Means Linear Regression Summary",
            covariate.labels = "Time",
            report = "vc*spt",
            out = paste(parent_dir,"/data_summaries/summary_tables/",proj_dep_name,"_monthly_means_regression_summary.txt",sep=""))

  ##### mean daily per month by stratum #####
  if("Strata" %in% names(daily_site_summary)){
    Event_monthly_means_stratum <- daily_site_summary %>%
      dplyr::group_by(Year,Month,Strata) %>%
      dplyr::summarise(
        MeanDailyEvents = if(all(is.na(total_Events))) NA_real_
        else mean(total_Events, na.rm=TRUE),
        sdDailyEvents = if(all(is.na(total_Events))) NA_real_
        else sd(total_Events, na.rm=TRUE),
        n = n(),
        seDailyEvents = sdDailyEvents/sqrt(n),
        maxDailyEvents = if(all(is.na(total_Events))) NA_real_
        else max(total_Events, na.rm=TRUE),
        minDailyEvents = if(all(is.na(total_Events))) NA_real_
        else min(total_Events, na.rm=TRUE),
        sumEvents = if(all(is.na(total_Events))) NA_real_
        else sum(total_Events, na.rm=TRUE),
        sumNightEvents = if(all(is.na(night_total))) NA_real_
        else sum(night_total,na.rm=TRUE),
        meanNightEvents = if(all(is.na(night_total))) NA_real_
        else mean(night_total,na.rm=TRUE),
        proportionNightEvents = sumNightEvents/sumEvents
      )
    sum(Event_monthly_means_stratum$sumEvents, na.rm=T) #36236
    Event_monthly_means_stratum$`Year-Month` <- as.Date(paste(Event_monthly_means_stratum$Year, Event_monthly_means_stratum$Month, "01", sep = "-"))
    write.table(Event_monthly_means_stratum,
                paste0(parent_dir,"/data_summaries/summary_tables/",proj_dep_name,"_PNNN_Events_ZeroDays_soundExcluded_3randDaysOnly_MonthlyMean_Stratum.txt"),
                sep='\t',na="",col.names=TRUE,row.names=FALSE, quote=FALSE, append=FALSE)
  }

  # plot monthly means per stratum
  if("Strata" %in% names(daily_site_summary)){
    # First create a grouping variable for consecutive months
    Event_monthly_means_stratum <- Event_monthly_means_stratum %>%
      arrange(Strata, `Year-Month`) %>%
      group_by(Strata) %>%
      mutate(month_group = cumsum(c(TRUE, diff(as.numeric(`Year-Month`)) > 31))) %>%
      ungroup()

    Event_monthly_means_stratum_plot <- ggplot(as.data.frame(Event_monthly_means_stratum),
                                                aes(x=`Year-Month`,y=MeanDailyEvents))+
      geom_errorbar(aes(ymin=MeanDailyEvents-seDailyEvents,
                        ymax=MeanDailyEvents+seDailyEvents),
                    width=.1) +
      # Modified geom_line to use the grouping variable
      geom_line(aes(group = month_group), color = "dark blue")+
      geom_point()+
      stat_summary(fun.data=mean_cl_normal)+
      geom_smooth(method='lm', aes(color = Strata)) +
      scale_color_viridis_d()+
      facet_wrap(~Strata)+
      scale_x_date(date_breaks = "6 months",
                   date_labels = "%b-%Y")+
      scale_y_continuous()+
      theme(axis.text.x = element_text(angle = 60, hjust = 1),
            plot.title = element_text(hjust = 0.5),
            panel.grid.major = element_line(colour = "white"),
            panel.grid.minor = element_blank())+
      labs(title = "Average Number of Events per Day per Month by Stratum",
           x = "Date (Month-Year)",
           y = "Average Number of Events per Day (+/- SE)")
  }

  # plot monthly means with stratum together (note that month 38 has 0 detections. Check sound check for this month)
  if("Strata" %in% names(daily_site_summary)){
    # Create complete time series
    all_dates <- seq.Date(
      from = min(Event_monthly_means_stratum$`Year-Month`, na.rm=TRUE),
      to = max(Event_monthly_means_stratum$`Year-Month`, na.rm=TRUE),
      by = "month"
    )
    all_strata <- unique(Event_monthly_means_stratum$Strata)
    complete_grid <- expand.grid(
      `Year-Month` = all_dates,
      Strata = all_strata
    ) %>% as_tibble()
    Event_monthly_complete <- left_join(
      complete_grid,
      Event_monthly_means_stratum,
      by = c("Year-Month", "Strata")
    )

    # Create the plot with complete data
    Event_monthly_means_stratum_plot_overlay <- ggplot(as.data.frame(Event_monthly_complete),
                                                        aes(x=`Year-Month`, y=MeanDailyEvents, color=Strata))+
      geom_errorbar(aes(ymin=MeanDailyEvents-seDailyEvents,
                        ymax=MeanDailyEvents+seDailyEvents),
                    width=.1, alpha=0.5) +
      geom_line() +
      geom_point()+
      stat_summary(fun.data=mean_cl_normal)+
      geom_smooth(method='lm', aes(fill = Strata), alpha = 0.2) +
      scale_color_viridis_d() +
      scale_fill_viridis_d() +
      scale_x_date(date_breaks = "6 months",
                   date_labels = "%b-%Y")+
      scale_y_continuous()+
      theme_bw() +
      theme(axis.text.x = element_text(angle = 60, hjust = 1),
            plot.title = element_text(hjust = 0.5),
            panel.grid.major = element_line(colour = "gray90"),
            panel.grid.minor = element_blank(),
            legend.position = "top")+
      labs(title = "Average Number of Events per Day per Month by Stratum",
           x = "Date (Month-Year)",
           y = "Average Number of Events per Day (+/- SE)")
  }

  # Regression model monthly means per strata
  if("Strata" %in% names(daily_site_summary)){
    # convert dates to a numeric value (days since start)
    Event_monthly_complete <- Event_monthly_complete %>%
      mutate(days_since_start = as.numeric(`Year-Month` - min(`Year-Month`)))
    # Create models using the same date format as ggplot
    strata_models <- Event_monthly_complete %>%
      group_by(Strata) %>%
      nest() %>%
      mutate(
        model = map(data, ~lm(MeanDailyEvents ~ days_since_start, data = .x))
      )
    model_list <- strata_models$model
    names(model_list) <- strata_models$Strata
    stargazer(model_list,
              type = "text",
              title = "Regression Results by Stratum",
              column.labels = strata_models$Strata,
              intercept.bottom = FALSE,
              report = "vc*spt",
              out = paste0(parent_dir,"/data_summaries/summary_tables/",proj_dep_name,"_stratum_regression_results.txt"))
  }


  #### SAVE PLOTS ####
  # List all default plots
  save_list <- list(
    total_plot = events_hrly_Date_plot,
    night_day_plot = events_hrly_nightday_plot,
    hourly_plot = events_hr_plot,

    daily_plot_site = Events_daily_site_plot,
    weekly_plot_site = EventWklySite,
    monthly_plot = Event_monthly_means_plot,
    monthly_plot_site = Event_monthly_means_site_plot
  )

  # Add strata plots if applicable
  if("Strata" %in% names(daily_site_summary)){
    save_list <- c(
      save_list,
      list(
        daily_plot_strata = Events_daily_strata_plot,
        weekly_plot_strata = EventWklyStrata,
        monthly_plot_strata = Event_monthly_means_stratum_plot,
        monthly_plot_strata_overlay = Event_monthly_means_stratum_plot_overlay
      )
    )
  }

  # Add vegetation class plots if applicable
  if("Vegetation Class" %in% names(daily_site_summary)){
    save_list <- c(
      save_list,
      list(
        daily_plot_veg = Events_daily_veg_plot,
        weekly_plot_veg = EventWklyVeg
      )
    )
  }

  # Write all plots into an .Rds file
  saveRDS(save_list, paste0(parent_dir,"/data_summaries/summary_plots/",proj_dep_name,"_saved_plots.Rds"))

  # Save each plot in the list as a separate PNG file
  for (plot_name in names(save_list)) {
    plot_data <- save_list[[plot_name]]$data
    if (is.data.frame(plot_data) && nrow(plot_data) == 0) {
      warning("Skipping PNG for plot with no data: ", plot_name)
    } else {
      data_description <- if (is.data.frame(plot_data)) paste(nrow(plot_data), "rows") else "layer-defined data"
      print(paste("Saving plot:", plot_name, "with", data_description))
      safe_ggsave(
        filename = paste0(parent_dir,"/data_summaries/summary_plots/",proj_dep_name,"_",plot_name,".png"),
        plot = save_list[[plot_name]],
        width = 10,
        height = 8
      )
    }
  }


  setwd(og_dir)
  print("Running data_summaries_function complete.")
  return("Finished!")

}


### Troubleshooting ####
# output<- rstudioapi::selectDirectory(caption = "Select folder for the output to be saved",label = "Select",path = getwd())
# sound_checks <- rstudioapi::selectDirectory(caption = "Select folder containing 'sound check' files",label = "Select",path = getwd())
# selection_tables <- rstudioapi::selectDirectory(caption = "Select folder containing selection tables",label = "Select",path = getwd())
# zero_txt <- rstudioapi::selectDirectory(caption = "Select folder containing 'zero days' selection tables",label = "Select",path = getwd())
#
# # choose the site file with latitude, longitude, "vegetation Class" (optional), "strata" (optional)
# site_lat_long <- read.table("C:/Users/bje37/Documents/GitHub/elpR_Shiny/files_for_elpR/sites/DSPA_DZ_Sites.txt",
#                             header = T, sep ="\t", check.names=FALSE,quote = "\"")# load general table for sites
#
# project_name <- "Dzanga" # name of project (e.g., "PNNN", "DzangaBai", "Kakum", etc.)
# deployment_num <- "01-06" # deployment(s) number (e.g., "01-12", "04")
# detector_name <- "HHv6" # # name of the detector used for these data. For HoriHarm:HHv6, FruitPunchAI: FPv1, Stanford Detector: SDv1. For other, type the name. Do not include spaces or special characters
#
# fileDurationMin <- 360 # duration in minutes of the expected sound file duration (60 for 1 hr, 1440 for 1 day)
# sound_check_include <- "y" # if you have a sound_check file for this script to filter out bad sounds, choose "y", otherwise choose "n"
# rand_dates_needed <- "y" # type "y" if so, type "n" of not
# #zeroDays_table_exist <- "y" # if you used the Event selection table restructure R script from the elpR package to restructure selection tables, a 'Zero Days' file was created. Select it from the folder above and choose "y". If not, choose "n"
# events_bad_sound_remove <- "y" # type "y" if sounds with <23 hrs of sound should be excluded. Type "n" if not
# use_only_sites_provided <- "y" # choose "y" if you only want to include the sites that were listed in the site_lat_long file. This enables exclusion of other sites that may be in the selection tables.
# # NOT IN YET: use_only_files_in_soundCheck <- "y" # do you want to exclude selections that do not occur on sound files listed in the sound check?
# # create map of results <- "y" # do you want the data plottod on a map ("y" if yes)?
