#' @title Maps
#' @author Jidapa Janpathompong
#'
#' @description This function reads tables generated by data_summaries_function() and
#' creates maps to be visualized in elpRApp().
#'
#' @param folder_path Path to folder containing output from data_summaries_function(). ***Needs to be in /data_summaries/summary_tables if running this function from shiny app in elpRApp().
#' @param site_lat_long Path to a .txt file containing site names with latitude, longitude, strata (optional), vegetation class (optional): See existing files in the "elpR/Files/sites" folder for required structure of .txt file
#'
#' @returns This function outputs a list containing tables and leaflet maps:
#' \itemize{
#'  \item event_site_avg: a table summarizing average daily events per site
#'  \item event_year_avg: a table summarizing average daily events per site per year
#'  \item event_month_avg: a table summarizing average daily events per site per month
#'  \item default_map: a leaflet map displaying average daily events at each site
#'  \item strata_map: a leaflet map displaying average daily events at each site, with sites colored by strata
#'  \item veg_map: a leaflet map displaying average daily events at each site, with sites colored by vegetation class
#'  \item year_map: a leaflet map with sites colored by average daily events; data intended to be displayed in elpRApp()
#'  \item month_map: a leaflet map with sites colored by average daily events; data intended to be displayed in elpRApp()
#' }
#' @export

maps_function <- function(folder_path, site_lat_long){
  print("Running maps_function...")

  if (!dir.exists(folder_path)) {
    stop("Maps summary folder does not exist: ", folder_path)
  }
  if (!file.exists(site_lat_long)) {
    stop("Sites latitude/longitude file does not exist: ", site_lat_long)
  }

  #### LOAD TABLES ####
  #load tables from user inputted folder path
  weekly_files <- list.files(path = folder_path,
                             pattern = "Events_Site_Weekly_Summaries.txt",
                             full.names = TRUE)
  monthly_files <- list.files(path = folder_path,
                              pattern = "Events_ZeroDays_soundExcluded_3randDaysOnly_MonthlyMean_Site.txt",
                              full.names = TRUE)
  if (length(weekly_files) != 1) {
    stop("Expected exactly one Events weekly summary file; found ", length(weekly_files),
         " in ", folder_path)
  }
  if (length(monthly_files) != 1) {
    stop("Expected exactly one Events monthly summary file; found ", length(monthly_files),
         " in ", folder_path)
  }
  events_weekly <- read_tsv(
    weekly_files,
    col_names = TRUE)
  events_monthly_site <- read_tsv(
    monthly_files,
    col_names = TRUE)
  site_lat_long_map <- read_tsv(
    site_lat_long,
    col_names = TRUE)

  required_weekly_columns <- c("Site", "Latitude", "Longitude", "sumEvents", "n")
  missing_weekly_columns <- setdiff(required_weekly_columns, names(events_weekly))
  if (length(missing_weekly_columns) > 0) {
    stop("Weekly Events summary is missing columns: ", paste(missing_weekly_columns, collapse = ", "))
  }
  required_monthly_columns <- c("Site", "Year", "Month", "sumEvents", "n")
  missing_monthly_columns <- setdiff(required_monthly_columns, names(events_monthly_site))
  if (length(missing_monthly_columns) > 0) {
    stop("Monthly Events summary is missing columns: ", paste(missing_monthly_columns, collapse = ", "))
  }
  missing_site_columns <- setdiff(c("Site", "Latitude", "Longitude"), names(site_lat_long_map))
  if (length(missing_site_columns) > 0) {
    stop("Sites file is missing columns: ", paste(missing_site_columns, collapse = ", "))
  }

  #### CONFIGURE TABLES ####
  #initialize empty list to hold this function's outputs
  output_list <- list()

  #make tables summarizing avg daily Events per site
  if("Vegetation Class" %in% names(events_weekly) &&
     "Strata" %in% names(events_weekly)){
    #avg daily Events for "Strata" & "Vegetation Class"
    output_list <- c(
      output_list,
      list(
        event_site_avg =
          events_weekly %>%
          group_by(Site) %>%
          summarize(
            "Latitude" = round(first(Latitude),5),
            "Longitude" = round(first(Longitude),5),
            "Avg Events" = sum(sumEvents)/sum(n),
            "Strata" = first(Strata),
            "Vegetation Class" = first(`Vegetation Class`)
          )
      )
    )
  } else if("Strata" %in% names(events_weekly)){
    #avg daily Events for "Strata"
    output_list <- c(
      output_list,
      list(
        event_site_avg =
          events_weekly %>%
          group_by(Site) %>%
          summarize(
            "Latitude" = round(first(Latitude),5),
            "Longitude" = round(first(Longitude),5),
            "Avg Events" = sum(sumEvents)/sum(n),
            "Strata" = first(Strata)
          )
      )
    )
  } else if("Vegetation Class" %in% names(events_weekly)){
    #avg daily Events for "Vegetation Class"
    output_list <- c(
      output_list,
      list(
        event_site_avg =
          events_weekly %>%
          group_by(Site) %>%
          summarize(
            "Latitude" = round(first(Latitude),5),
            "Longitude" = round(first(Longitude),5),
            "Avg Events" = sum(sumEvents)/sum(n),
            "Vegetation Class" = first(`Vegetation Class`)
          )
      )
    )
  } else{
    #avg daily Events with NO "Strata" NOR "Vegetation Class"
    output_list <- c(
      output_list,
      list(
        event_site_avg =
          events_weekly %>%
          group_by(Site) %>%
          summarize(
            "Latitude" = round(first(Latitude),5),
            "Longitude" = round(first(Longitude),5),
            "Avg Events" = sum(sumEvents)/sum(n)
          )
      )
    )
  }

  output_list <- c(
    output_list,
    list(
      #avg daily Events for "Year"
      event_year_avg =
        events_monthly_site %>%
        group_by(Site, Year) %>%
        summarize(
          "Avg Events" = sum(sumEvents)/sum(n)
        ) %>%
        merge(site_lat_long_map, by = "Site"),

      #avg daily Events for "Month"
      event_month_avg =
        events_monthly_site %>%
        group_by(Site, Month) %>%
        summarize(
          "Avg Events" = sum(sumEvents)/sum(n)
        ) %>%
        merge(site_lat_long_map, by = "Site")
    )
  )

  #### CREATE MAPS####
  #retrieve configured tables
  event_site_avg <- output_list$event_site_avg
  event_year_avg <- output_list$event_year_avg
  event_month_avg <- output_list$event_month_avg

  #BASE MAP - set lat & long
  base_map <- leaflet(event_site_avg) %>%

    #Add default base map
    addProviderTiles(provider = providers$Esri.WorldTopoMap,
                     group = "map") %>%

    #Set center point and zoom level
    setView(lng = mean(event_site_avg$Longitude),
            lat = mean(event_site_avg$Latitude),
            zoom = 10)

  #DEFAULT MAP - add circle markers for avg Events
  default_map <- base_map %>%

    #Add markers
    addCircleMarkers(
      lng = ~Longitude,
      lat = ~Latitude,
      radius = ~sqrt(`Avg Events`) * 10,  # Adjust the multiplier to change circle sizes
      popup = ~paste("Site:", Site, "<br>Avg Events:", `Avg Events`),
      fillOpacity = 0.7
    )

  #STRATA MAP - add circle markers for avg Events & color by strata
  color_by_strata <- colorFactor(palette = "viridis",
                                 domain = unique(event_site_avg$Strata))
  strata_map <- base_map %>%

    #Add legend
    addLegend(
      position = "bottomright",
      pal = color_by_strata,
      values = ~Strata,
      title = "Strata"
    ) %>%

    #Add layers control
    addLayersControl(overlayGroups = unique(event_site_avg$Strata),
                     position = "topleft")

  #Add markers
  for(strata in unique(event_site_avg$Strata)){
    subset_data <- event_site_avg %>%
      filter(Strata == strata)

    strata_map <- strata_map %>%
      addCircleMarkers(
        data = subset_data,
        lng = ~Longitude,
        lat = ~Latitude,
        radius = ~sqrt(`Avg Events`) * 10,  # Adjust the multiplier to change circle sizes
        popup = ~paste("Site:", Site, "<br>Avg Events:", `Avg Events`),
        color = ~color_by_strata(Strata),
        fillOpacity = 0.7,
        group = paste(strata)
      )
  }

  #VEGETATION CLASS MAP - add circle markers for avg Events & color by veg class
  color_by_veg <- colorFactor(palette = "plasma",
                              domain = unique(event_site_avg$`Vegetation Class`))
  veg_map <- base_map %>%

    #Add legend
    addLegend(
      position = "bottomright",
      pal = color_by_veg,
      values = ~`Vegetation Class`,
      title = "Vegetation Class"
    ) %>%

    #Add layers control
    addLayersControl(overlayGroups = unique(event_site_avg$`Vegetation Class`),
                     position = "topleft")

  #Add markers
  for(veg in unique(event_site_avg$`Vegetation Class`)){
    subset_data <- event_site_avg %>%
      filter(`Vegetation Class` == veg)

    veg_map <- veg_map %>%
      addCircleMarkers(
        data = subset_data,
        lng = ~Longitude,
        lat = ~Latitude,
        radius = ~sqrt(`Avg Events`) * 10,  # Adjust the multiplier to change circle sizes
        popup = ~paste("Site:", Site, "<br>Avg Events:", `Avg Events`),
        color = ~color_by_veg(`Vegetation Class`),
        fillOpacity = 0.7,
        group = paste(veg)
      )
  }

  #YEAR MAP - add circle markers for avg Events & color by avg Events
  color_by_Events <- colorNumeric(palette = "viridis",
                                   domain = range(event_year_avg$`Avg Events`))
  year_map <- leaflet(event_year_avg) %>%

    #Add default base map
    addProviderTiles(provider = providers$Esri.WorldTopoMap,
                     group = "map") %>%

    #Set center point and zoom level
    setView(lng = mean(event_year_avg$Longitude),
            lat = mean(event_year_avg$Latitude),
            zoom = 10) %>%

    #Add legend
    addLegend(
      position = "bottomright",
      pal = color_by_Events,
      values = ~`Avg Events`,
      title = "Avg Daily Events"
    )

  #MONTH MAP - add circle markers for avg Events & color by avg Events
  color_by_Events <- colorNumeric(palette = "viridis",
                                   domain = range(event_month_avg$`Avg Events`))
  month_map <- leaflet(event_month_avg) %>%

    #Add default base map
    addProviderTiles(provider = providers$Esri.WorldTopoMap,
                     group = "map") %>%

    #Set center point and zoom level
    setView(lng = mean(event_month_avg$Longitude),
            lat = mean(event_month_avg$Latitude),
            zoom = 10) %>%

    #Add legend
    addLegend(
      position = "bottomright",
      pal = color_by_Events,
      values = ~`Avg Events`,
      title = "Avg Daily Events"
    )

  #save maps to output list
  output_list <- c(
    output_list,
    list(
      default_map = default_map,
      strata_map = strata_map,
      veg_map = veg_map,
      year_map = year_map,
      month_map = month_map
    )
  )

  #### RETURN ####
  print("Running maps_function complete.")
  #return configured tables and maps
  return(output_list)
}
