#' @title Maps
#' @author Jidapa Janpathompong
#'
#' @description This function reads tables generated by data_summaries_function() and
#' creates maps to be visualized in elpRApp().
#'
#' @param folder_path Path to folder containing output from data_summaries_function(). ***Needs to be in /data_summaries/summary_tables if running this function from shiny app in elpRApp().
#' @param site_lat_long Path to a .txt file containing site names with latitude, longitude, strata (optional), vegetation class (optional): See existing files in the "elpR/Files/sites" folder for required structure of .txt file
#'
#' @returns This function outputs a list containing tables and leaflet maps:
#' \itemize{
#'  \item ele_site_avg: a table summarizing average daily rumbles per site
#'  \item ele_year_avg: a table summarizing average daily rumbles per site per year
#'  \item ele_month_avg: a table summarizing average daily rumbles per site per month
#'  \item default_map: a leaflet map displaying average daily rumbles at each site
#'  \item strata_map: a leaflet map displaying average daily rumbles at each site, with sites colored by strata
#'  \item veg_map: a leaflet map displaying average daily rumbles at each site, with sites colored by vegetation class
#'  \item year_map: a leaflet map with sites colored by average daily rumbles; data intended to be displayed in elpRApp()
#'  \item month_map: a leaflet map with sites colored by average daily rumbles; data intended to be displayed in elpRApp()
#' }
#' @export

maps_function <- function(folder_path, site_lat_long){
  print("Running maps_function...")

  #### LOAD TABLES ####
  #load tables from user inputted folder path
  ele_weekly <- read_tsv(paste0(
    folder_path,
    list.files(path = folder_path,
               pattern = "Rumbles_Site_Weekly_Summaries.txt")
    ),
    col_names = TRUE)
  ele_monthly_site <- read_tsv(paste0(
    folder_path,
    list.files(path = folder_path,
               pattern = "Rumbles_ZeroDays_soundExcluded_3randDaysOnly_MonthlyMean_Site.txt")
    ),
    col_names = TRUE)
  site_lat_long_map <- read_tsv(
    site_lat_long,
    col_names = TRUE)

  #### CONFIGURE TABLES ####
  #initialize empty list to hold this function's outputs
  output_list <- list()

  #make tables summarizing avg daily rumbles per site
  if("Vegetation Class" %in% names(ele_weekly) &&
     "Strata" %in% names(ele_weekly)){
    #avg daily rumbles for "Strata" & "Vegetation Class"
    output_list <- c(
      output_list,
      list(
        ele_site_avg =
          ele_weekly %>%
          group_by(Site) %>%
          summarize(
            "Latitude" = round(first(Latitude),5),
            "Longitude" = round(first(Longitude),5),
            "Avg Rumbles" = sum(sumRumbles)/sum(n),
            "Strata" = first(Strata),
            "Vegetation Class" = first(`Vegetation Class`)
          )
      )
    )
  } else if("Strata" %in% names(ele_weekly)){
    #avg daily rumbles for "Strata"
    output_list <- c(
      output_list,
      list(
        ele_site_avg =
          ele_weekly %>%
          group_by(Site) %>%
          summarize(
            "Latitude" = round(first(Latitude),5),
            "Longitude" = round(first(Longitude),5),
            "Avg Rumbles" = sum(sumRumbles)/sum(n),
            "Strata" = first(Strata)
          )
      )
    )
  } else if("Vegetation Class" %in% names(ele_weekly)){
    #avg daily rumbles for "Vegetation Class"
    output_list <- c(
      output_list,
      list(
        ele_site_avg =
          ele_weekly %>%
          group_by(Site) %>%
          summarize(
            "Latitude" = round(first(Latitude),5),
            "Longitude" = round(first(Longitude),5),
            "Avg Rumbles" = sum(sumRumbles)/sum(n),
            "Vegetation Class" = first(`Vegetation Class`)
          )
      )
    )
  } else{
    #avg daily rumbles with NO "Strata" NOR "Vegetation Class"
    output_list <- c(
      output_list,
      list(
        ele_site_avg =
          ele_weekly %>%
          group_by(Site) %>%
          summarize(
            "Latitude" = round(first(Latitude),5),
            "Longitude" = round(first(Longitude),5),
            "Avg Rumbles" = sum(sumRumbles)/sum(n)
          )
      )
    )
  }

  output_list <- c(
    output_list,
    list(
      #avg daily rumbles for "Year"
      ele_year_avg =
        ele_monthly_site %>%
        group_by(Site, Year) %>%
        summarize(
          "Avg Rumbles" = sum(sumRumbles)/sum(n)
        ) %>%
        merge(site_lat_long_map, by = "Site"),

      #avg daily rumbles for "Month"
      ele_month_avg =
        ele_monthly_site %>%
        group_by(Site, Month) %>%
        summarize(
          "Avg Rumbles" = sum(sumRumbles)/sum(n)
        ) %>%
        merge(site_lat_long_map, by = "Site")
    )
  )

  #### CREATE MAPS####
  #retrieve configured tables
  ele_site_avg <- output_list$ele_site_avg
  ele_year_avg <- output_list$ele_year_avg
  ele_month_avg <- output_list$ele_month_avg

  #BASE MAP - set lat & long
  base_map <- leaflet(ele_site_avg) %>%

    #Add default base map
    addProviderTiles(provider = providers$Esri.WorldTopoMap,
                     group = "map") %>%

    #Set center point and zoom level
    setView(lng = mean(ele_site_avg$Longitude),
            lat = mean(ele_site_avg$Latitude),
            zoom = 10)

  #DEFAULT MAP - add circle markers for avg rumbles
  default_map <- base_map %>%

    #Add markers
    addCircleMarkers(
      lng = ~Longitude,
      lat = ~Latitude,
      radius = ~sqrt(`Avg Rumbles`) * 10,  # Adjust the multiplier to change circle sizes
      popup = ~paste("Site:", Site, "<br>Avg Rumbles:", `Avg Rumbles`),
      fillOpacity = 0.7
    )

  #STRATA MAP - add circle markers for avg rumbles & color by strata
  color_by_strata <- colorFactor(palette = "viridis",
                                 domain = unique(ele_site_avg$Strata))
  strata_map <- base_map %>%

    #Add legend
    addLegend(
      position = "bottomright",
      pal = color_by_strata,
      values = ~Strata,
      title = "Strata"
    ) %>%

    #Add layers control
    addLayersControl(overlayGroups = unique(ele_site_avg$Strata),
                     position = "topleft")

  #Add markers
  for(strata in unique(ele_site_avg$Strata)){
    subset_data <- ele_site_avg %>%
      filter(Strata == strata)

    strata_map <- strata_map %>%
      addCircleMarkers(
        data = subset_data,
        lng = ~Longitude,
        lat = ~Latitude,
        radius = ~sqrt(`Avg Rumbles`) * 10,  # Adjust the multiplier to change circle sizes
        popup = ~paste("Site:", Site, "<br>Avg Rumbles:", `Avg Rumbles`),
        color = ~color_by_strata(Strata),
        fillOpacity = 0.7,
        group = paste(strata)
      )
  }

  #VEGETATION CLASS MAP - add circle markers for avg rumbles & color by veg class
  color_by_veg <- colorFactor(palette = "plasma",
                              domain = unique(ele_site_avg$`Vegetation Class`))
  veg_map <- base_map %>%

    #Add legend
    addLegend(
      position = "bottomright",
      pal = color_by_veg,
      values = ~`Vegetation Class`,
      title = "Vegetation Class"
    ) %>%

    #Add layers control
    addLayersControl(overlayGroups = unique(ele_site_avg$`Vegetation Class`),
                     position = "topleft")

  #Add markers
  for(veg in unique(ele_site_avg$`Vegetation Class`)){
    subset_data <- ele_site_avg %>%
      filter(`Vegetation Class` == veg)

    veg_map <- veg_map %>%
      addCircleMarkers(
        data = subset_data,
        lng = ~Longitude,
        lat = ~Latitude,
        radius = ~sqrt(`Avg Rumbles`) * 10,  # Adjust the multiplier to change circle sizes
        popup = ~paste("Site:", Site, "<br>Avg Rumbles:", `Avg Rumbles`),
        color = ~color_by_veg(`Vegetation Class`),
        fillOpacity = 0.7,
        group = paste(veg)
      )
  }

  #YEAR MAP - add circle markers for avg rumbles & color by avg rumbles
  color_by_rumbles <- colorNumeric(palette = "viridis",
                                   domain = range(ele_year_avg$`Avg Rumbles`))
  year_map <- leaflet(ele_year_avg) %>%

    #Add default base map
    addProviderTiles(provider = providers$Esri.WorldTopoMap,
                     group = "map") %>%

    #Set center point and zoom level
    setView(lng = mean(ele_year_avg$Longitude),
            lat = mean(ele_year_avg$Latitude),
            zoom = 10) %>%

    #Add legend
    addLegend(
      position = "bottomright",
      pal = color_by_rumbles,
      values = ~`Avg Rumbles`,
      title = "Avg Daily Rumbles"
    )

  #MONTH MAP - add circle markers for avg rumbles & color by avg rumbles
  color_by_rumbles <- colorNumeric(palette = "viridis",
                                   domain = range(ele_month_avg$`Avg Rumbles`))
  month_map <- leaflet(ele_month_avg) %>%

    #Add default base map
    addProviderTiles(provider = providers$Esri.WorldTopoMap,
                     group = "map") %>%

    #Set center point and zoom level
    setView(lng = mean(ele_month_avg$Longitude),
            lat = mean(ele_month_avg$Latitude),
            zoom = 10) %>%

    #Add legend
    addLegend(
      position = "bottomright",
      pal = color_by_rumbles,
      values = ~`Avg Rumbles`,
      title = "Avg Daily Rumbles"
    )

  #save maps to output list
  output_list <- c(
    output_list,
    list(
      default_map = default_map,
      strata_map = strata_map,
      veg_map = veg_map,
      year_map = year_map,
      month_map = month_map
    )
  )

  #### RETURN ####
  print("Running maps_function complete.")
  #return configured tables and maps
  return(output_list)
}
